/**
 * Enum representing the possible icon svg.
 */
export enum EIcon {
  En = 'en',
  Vi = 'vi',
  Out = 'out',
  DayNight = 'day-night',
  Logo = 'logo',
  EyeSlash = 'eye-slash',
  Eye = 'eye',
  Success = 'success',
  Error = 'error',
  Confirm = 'confirm',
  Warning = 'warning',
  Close = 'close',
  Check = 'check',
  Arrow = 'arrow',
  Calendar = 'calendar',
  Upload = 'upload',
  Paste = 'paste',
  Search = 'search',
  DoubleArrow = 'double-arrow',
  Filter = 'filter',
  FilterFill = 'filter-fill',
  Sort = 'sort',
  Facebook = 'facebook',
  Linkedin = 'linkedin',
  X = 'x',
  Twitter = 'twitter',
  Instagram = 'instagram',
  Phone = 'phone',
  Email = 'email',
  Clock = 'clock',
  Location = 'location',
  Arrow_Down = 'arrow_down',
  Arrow_Right = 'arrow_right',
  Business_Money = 'business_money',
  Double_Check = 'double_check',
  Hamburger = 'hamburger',
  Flaticon = 'flaticon',  
  Star = 'star',
  Calender = 'calender',
  Tag = 'tag',
  WhatApp = 'whatapp',
  Send = 'send',
}